# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52f34a348b4d48a55abfbeb6f743713117c90d41d8eeccad96a835f98f5b63a8c288b1533693ff12c70e13b449c5d8f9eb9f2ca585b4f0a856210f65c4c90192

test:
  secret_key_base: bc114adde550a0c50271f7b62154f1b83b2519344ba7618dbbda42e9b42b3a528f68def05e7a46603de43588f4581ad614916423cdd8e77e213b93b81555b987

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
